### PR TITLE
Add "not" validator in Number validators

### PR DESCRIPTION
**Pull request by GreatWizard**
I need to be sure that the user choose a number differents to another one.

I can make a second PR on ember-cp-validations to update the documentation if you want :)

### CODE REVIEW

**Comment by offirgolan** [comment]
@GreatWizard all of these `not` and `is` options can be solved by just using the `inclusion` and `exclusion` validators. Ember-cp-validations also provides a `value` option to modify your value before it is sent to the validator (good for formatting your date string 😉 ).

**Comment by GreatWizard** [comment]
I understand your point, but.. why do we have the `positive` validator ? it's a `gte 0`

**Comment by offirgolan** [comment]
@GreatWizard great point lol. `positive` was actually part of the original rails number validator (where this library grew from) and taking it out would force me to make a major release.... I just find it easier to just leave it in there for now 😄

**Comment by GreatWizard** [comment]
I close this PR
thanks @offirgolan

**Pull request closed without merging**
