### PR TITLE
Upgrades + Embroider compatibility

### PR DESCRIPTION
**Pull request by thoov**
This PR includes:

- ember-cli-upgrade changes
- changes to `addon/index.js` such that there are no "dynamic" requires
- adds @embroider/test-setup to ember-try's scenarios

Currently blocked by: embroider-build/embroider#826

Apart of: ember-cli/ember-cli#9536

### CODE REVIEW

**Comment by snewcomer** [comment]
@thoov 

Should we throw in these changes to this PR as well?  (still have to get past this "Required" check that is in the Settings tab that I don't have access to.

https://github.com/offirgolan/ember-validators/pull/93

**Comment by snewcomer** [comment]
I think we can give Github Actions a shot.  The travis CI req has been removed!

**Comment by snewcomer** [comment]
👋 Any way I can help here?

**Comment by josemarluedke** [comment]
I'm also looking forward to this.

**Pull request closed without merging**
