### PR TITLE
Avoid options mutation

### PR DESCRIPTION
**Pull request by betocantu93**
Noticed format and date mutate te options hash, this causes trouble for the new tracking system in octane

### CODE REVIEW

**Comment by snewcomer** [comment]
This would be good to get in.  Need to merge in master though.  Significant updates to the date helper though 😞

**Comment by betocantu93** [comment]
hello @snewcomer wondering if this still needed with the last release? so I can merge in master?

**Comment by betocantu93** [comment]
closed in favor of #119

**Comment by snewcomer** [comment]
Yes I think it is but I imagine there is a test you can add!

**Comment by betocantu93** [comment]
I agree a test could be useful, but If I can recall correctly it has something to do with the double render issues in some autotracking situations and so to be honest reproducing a test in this repo could be hard. In my opinion, these functions should not need to know what context they're running in (autotracking, etc) they should be pure stateless functions, which makes me wonder if Object.assign is still _not_ o.k., and that we _should_ be cloning instead

**Comment by betocantu93** [comment]
I can add a test ensuring we don't mutate

**Pull request closed without merging**
