### PR TITLE
Correct `present` message

### PR DESCRIPTION
**Pull request by sagelliv**

### CODE REVIEW

**Comment by offirgolan** [comment]
@sagelliv what is the reason for this PR?

**Comment by sagelliv** [comment]
It appears there is another [PR](https://github.com/offirgolan/ember-validators/pull/51) which address this.

**Comment by offirgolan** [comment]
@sagelliv are you using this library directly or are you coming here from ember-changeset-validations?

**Comment by sagelliv** [comment]
Hey @offirgolan, coming here from ember-changeset-validations: Upon using the most up to date version of that addon (and consequently this dependency) the validation messages were messed up.

**Comment by offirgolan** [comment]
@sagelliv this has been discussed in DockYard/ember-changeset-validations#140. Im gonna go ahead and close this since the solution will be handled there.

**Comment by sagelliv** [comment]
Sounds good @offirgolan, thanks!

**Pull request closed without merging**
