### PR TITLE
Remove use of deprecated getWithDefault API

### PR DESCRIPTION
**Pull request by JamesS-M**

### CODE REVIEW

**Comment by gilest** [comment]
Is it ok to use the `??` without a babel plugin?

**Comment by JamesS-M** [comment]
> Is it ok to use the `??` without a babel plugin?

Yes I believe you can!

**Comment by gilest** [comment]
Noticed the tests were failing so I had a go at fixing that in #78

Not sure if maintainer is active on this project though...

**Comment by offirgolan** [comment]
Not sure if `??` would work with older versions of ember. Can you replace it with `||`?

**Comment by JamesS-M** [comment]
> Not sure if `??` would work with older versions of ember. Can you replace it with `||`?

Absolutely!

**Comment by offirgolan** [comment]
Released with `v3.0.1`

**Pull request merged**
